# Generated by Django 4.2.1 on 2023-06-07 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BandUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=50)),
                ('bio', models.CharField(blank=True, max_length=50, null=True)),
                ('streaming', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BundleRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_title', models.CharField(max_length=50)),
                ('genre', models.CharField(blank=True, max_length=50)),
                ('upc', models.IntegerField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('artwork', models.CharField(blank=True, max_length=255)),
                ('uploaded_to_distro', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('date_created', models.DateField()),
                ('last_edited', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlists', to='bandplannerapi.banduser')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='bandplannerapi.banduser')),
            ],
        ),
        migrations.CreateModel(
            name='SingleRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=50)),
                ('genre', models.CharField(blank=True, max_length=50)),
                ('upc', models.IntegerField(blank=True)),
                ('isrc', models.IntegerField(blank=True)),
                ('composer', models.CharField(blank=True, max_length=50)),
                ('producer', models.CharField(blank=True, max_length=50)),
                ('explicit', models.BooleanField()),
                ('audio_url', models.URLField(blank=True)),
                ('artwork', models.CharField(blank=True, max_length=255)),
                ('uploaded_to_distro', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singlereleases', to='bandplannerapi.event')),
            ],
        ),
        migrations.CreateModel(
            name='SetlistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('setlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlists', to='bandplannerapi.setlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='bandplannerapi.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandplannerapi.banduser')),
            ],
        ),
        migrations.CreateModel(
            name='Rehearsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('band_info', models.TextField(blank=True, max_length=500)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsals', to='bandplannerapi.event')),
            ],
        ),
        migrations.CreateModel(
            name='PressClipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True)),
                ('author', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('link', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pressclippings', to='bandplannerapi.banduser')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField(blank=True, max_length=10000)),
                ('date_created', models.DateField()),
                ('last_edited', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='bandplannerapi.banduser')),
            ],
        ),
        migrations.CreateModel(
            name='MediaContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=50)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('media_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediacontacts', to='bandplannerapi.mediatype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediacontacts', to='bandplannerapi.banduser')),
            ],
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_state', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('band_info', models.TextField(blank=True, max_length=500)),
                ('age_requirement', models.CharField(blank=True, max_length=50)),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('ticket_link', models.URLField(blank=True)),
                ('guarantee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sold_out', models.BooleanField(default=False)),
                ('announced', models.BooleanField(default=False)),
                ('flier', models.CharField(blank=True, max_length=255)),
                ('stage_plot', models.CharField(blank=True, max_length=255)),
                ('input_list', models.CharField(blank=True, max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='bandplannerapi.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bandplannerapi.eventtype'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bandplannerapi.banduser'),
        ),
        migrations.CreateModel(
            name='BundleSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=50)),
                ('genre', models.CharField(blank=True, max_length=50)),
                ('isrc', models.IntegerField(blank=True)),
                ('composer', models.CharField(blank=True, max_length=50)),
                ('producer', models.CharField(blank=True, max_length=50)),
                ('explicit', models.BooleanField()),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundlesongs', to='bandplannerapi.bundlerelease')),
            ],
        ),
        migrations.AddField(
            model_name='bundlerelease',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundlereleases', to='bandplannerapi.event'),
        ),
        migrations.CreateModel(
            name='BandPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='bandplannerapi.banduser')),
            ],
        ),
    ]
