# Generated by Django 4.2.1 on 2023-06-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandplannerapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banduser',
            name='photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='BandPhoto',
        ),
    ]
