# Generated by Django 4.2.1 on 2023-06-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandplannerapi', '0002_alter_banduser_bio_alter_banduser_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='guarantee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
