# Generated by Django 4.2.3 on 2023-07-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandplannerapi', '0002_banduser_photo_delete_bandphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banduser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
