# Generated by Django 4.2.1 on 2023-06-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandplannerapi', '0003_alter_gig_guarantee'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacontact',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
